### PR TITLE
Code improvement

### PR DESCRIPTION
**Pull request by eminmuftic**
### Important issues to be considered in future

Before I talk about things I improved there is one which you need to be careful about in future. YOU LEFT YOUR API KEY, NEVER DO THAT!!! Be careful about that in future my friend please 😄. You should include something called **enviroment variables**. Those are variables which you can access anywhere in your project, but also those are variables which you ignore with git so that other people can't see them. And such a variable would be your apiKey. (Google it a bit it's important)

### Couple of things I improved

**1. States of your application**
In your case there are couple of states: 
-"There are no movies to display" state (it is a state when user opens application for the first time or if there are no movies for which he searced)
-"Loading" state (it is a state when user is waiting for movies to "come/load")
-"There are movies" state (it is a state where user gets movies)
-"Error" state (it is an error state... maybe network or authorization issuses...)

So just keep in mind that an application has different states and that states are very important for user experience, because there is a huge difference between "there are no movies" and "movies are on its way'

**2.Clean code, better code structure, logic and reusability**
This indeed is a small project, but if you were to work on a bigger one or in a team of more engineers it is important that you write clean and reusable code. 
-Make sure you write your variables, functions... concretely and precisely what they mean. For example in SearchBar.js you named variable as "text", now text can be anything right? But actually better name would be "enteredMovieTitle" because that is exactly what it is.
-You should also have a nice structure both of files and code itself, also you need to know what is it that you are doing 😃. In your case you rendered 90% of divs and that's not a best practice. Your app currently has two main sections or parts if you want to call them like that. First one is header and second one is main. In header you render your search bar and in main you render your movies list. Your search bar is indeed a form with one input and not a div with input, that's why you should rather listen to onSubmit() event than onEnteredKey() event (btw optionally you could have used useRef instead of working with useState and onChange event to get input value).  Also your movies list is indeed a list element with its items and not a bunch of divs. Yes...bunch of divs can work, you can also create a button as a div tag, but it's not a good practice that's what I'm trying to tell you.
-Try to make your code as reusable as possible. In this case one of the thing I've done is created a completely custom http hook. Reason why I did that is that later if your app is about to grow and you decide to add more stuff in it, your or anyone in your team who wants to create an http request can simply reuse the custom hook without writing the same logic for sending request a bunch of times. 
Also I changed folder structure a bit. Components folder now holds Layout and UI folders inside. Layout precisely holds different sections/parts of your app which indeed create your layout (in your case header with search bar and main with movies list). UI folder is again reusable folder where you hold all your reusable components (they can be custom reusable elements like: button, input, card... ), in this case I put loading spinner component that gets shown once it is loading state. By the way, in my case loading spinner is just an h1 tag that says "Loading...", but you should replace it with a div and proper styling to show a loading spinner.

### CODE REVIEW

**Comment by frankndungu** [comment]
Thanks so much ermin

**Comment by frankndungu** [comment]
Hey Emin, thank you so much for this. I'm still new at programming. I could really use your help on my projects do you mind if we kept in touch.

**Comment by eminmuftic** [comment]
No problem I would love to help. Any kind of social media you might have?

**Comment by eminmuftic** [comment]
Found you on LinkedIn. I've sent you the invitation to connect 😄

**Comment by frankndungu** [comment]
Already accepted your request

**Comment by frankndungu** [comment]
I am also on twitter what about you?

**Pull request merged**
